name: Test Secrets Access

on:
  push:
    branches:
      - main # 或者你的主分支

jobs:
  test_secrets_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secrets
        run: |
          echo "Attempting to access MY_TEST_VALUE: ${{ secrets.MY_TEST_VALUE }}"
          echo "Attempting to access EC2_HOST: ${{ secrets.EC2_HOST }}"